### ISSUE TITLE
Error Using `emulator.recommend()` When Using Dimensionality Reduction and Input Parameter Bounds

### ISSUE THREAD

**Issue by LucasPigott** [digiLab-ai/twinLab-Interface#3] opened 2024-07-24 15:50 UTC
**Describe the bug** A clear and concise description of what the bug is.

I am attempting to use `emulator.recommend()` containing a set of parameter bounds set through `twinlab.RecommendParams()`. When I run my example, I get an **Exception** with the message: **Exception: Error Code: 500 - Process recommend-exciting-cerulean-mice has failed: AssertionError: Provided bounds vectors dimensionality does not match number of inputs**

**What were you trying to do?** A description of what you were trying to achieve.

I am trying to use `emulator.recommend()` to suggest new data points within set parameter ranges to iteratively improve my emulator.

**What was the expected behaviour?** A description of what you expected to happen.

The code was expected to return a set of input values that would reduce the uncertainty in my emulator the most.

**What actually happened?** A description of what actually happened.

When the emulator was trained on sets of inputs and outputs in smaller dimensions, anywhere up to 10 dimensions for each, `emulator.predict()` worked as expected. However, for the following MWE and any higher dimensionality in the inputs or outputs, the above **Exception** was returned.

**To Reproduce** A set of explicit instructions for how to recreate the problem.

```toml
[tool.poetry.dependencies]
twinlab="2.10.0"
numpy ="1.26.4"  
pandas="2.2.2"                      
```

Here is my MWE:

```
import twinlab as tl

import numpy as np
import pandas as pd
```
```
# Number of input and output features
num_features = 11
num_rows = 2

# Generate column names for inputs and outputs
input_columns = [f'x_{i}' for i in range(1, num_features + 1)]
output_columns = [f'y_{i}' for i in range(1, num_features + 1)]

# Generate random data for inputs and outputs
data = {
    **{col: np.random.rand(num_rows) for col in input_columns},
    **{col: np.random.rand(num_rows) for col in output_columns},
}

# Create a DataFrame
df = pd.DataFrame(data)
df
```
```
param_ranges = {
    "x_1": (0,1),
    "x_2": (0,1),
    "x_3": (0,1),
    "x_4": (0,1),
    "x_5": (0,1),
    "x_6": (0,1),
    "x_7": (0,1),
    "x_8": (0,1),
    "x_9": (0,1),
    "x_10": (0,1),
    "x_11": (0,1),
}
```
```
# Intialise a Dataset object and give it a name
dataset = tl.Dataset('error_dataset')

# Upload the dataset, passing in the dataframe
dataset.upload(df[input_columns + output_columns])
```
```
# Initialise emulator
emulator_id = "example_emulator"

emulator = tl.Emulator(id=emulator_id)
```
```
# Define the training parameters for your emulator
params = tl.TrainParams(
    estimator='gaussian_process_regression',
    input_retained_dimensions=10,
    output_retained_dimensions=10
    )
```
```
# Train the emulator using the train method
emulator.train(
    dataset=dataset, inputs=input_columns, outputs=output_columns, params=params, verbose=True
)
```
```
parameters = tl.RecommendParams(bounds = param_ranges)
a,b = emulator.recommend(num_points=3, acq_func="LogEI", params = parameters ) 
a,b
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
Cell In[25], [line 2](vscode-notebook-cell:?execution_count=25&line=2)
      [1](vscode-notebook-cell:?execution_count=25&line=1) parameters = tl.RecommendParams(bounds = param_ranges)
----> [2](vscode-notebook-cell:?execution_count=25&line=2) a,b = emulator.recommend(num_points=3, acq_func="LogEI", params = parameters ) 
      [3](vscode-notebook-cell:?execution_count=25&line=3) a,b

File /opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1057, in recommend(self, num_points, acq_func, params, wait, verbose)
   [1054](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1054) if not wait:
   [1055](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1055)     return process_id
-> [1057](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1057) response = _utils.wait_for_job_completion(
   [1058](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1058)     _api.get_emulator_process, self.id, process_id, verbose=verbose
   [1059](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1059) )
   [1061](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1061) df, acq_func_value = EmulatorResultsAdapter("recommend", response).adapt_result(
   [1062](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1062)     verbose=verbose
   [1063](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1063) )
   [1065](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/emulator.py:1065) return df, acq_func_value

File /opt/venv/lib/python3.11/site-packages/twinlab/_utils.py:38, in wait_for_job_completion(api_function, verbose, *args)
     [36](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_utils.py:36) wait_time = _calculate_ping_time(elapsed_time)
     [37](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_utils.py:37) time.sleep(wait_time)
---> [38](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_utils.py:38) _, response = api_function(*args)
     [39](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_utils.py:39) status = ValidStatus(get_value_from_body("status", response))
     [40](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_utils.py:40) if verbose:
...
     [48](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_api/_utils.py:48)     else:
     [49](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_api/_utils.py:49)         message = body
---> [50](https://vscode-remote+codespaces-002bfantastic-002dspace-002dtrout-002dg456jx5457xr3vxpx.vscode-resource.vscode-cdn.net/opt/venv/lib/python3.11/site-packages/twinlab/_api/_utils.py:50) raise Exception(f"Error Code: {status} - {message}")

Exception: Error Code: 500 - Process recommend-exciting-cerulean-mice has failed: AssertionError: Provided bounds vectors dimensionality does not match number of inputs

**Screenshots** If applicable, add screenshots to help explain your problem.

**Business context** Add any business context that would help here.

This code aims to be applied onto a dataset with 15 input dimensions and 1000 output dimensions to build into a demo for active learning using `emulator.recommend()`.

**Comment by alexander-mead** [comment] 2024-07-25 10:26
Thanks for this. My initial suspicion is that this is caused by attempting to set bounds while at the same time applying functional decomposition. Were you expecting the bounds to apply to your original `X`, or were you attempting to place bounds on the `X'` created after SVD transformation?

**Comment by LucasPigott** [comment] 2024-07-25 10:45
Thank you for your response. I am attempting to place bounds to apply to my original `X` so that each recommended input parameter given by `emulator.recommend()` falls within the range set by these bounds.

**Comment by alexander-mead** [comment] 2024-07-25 13:19
I see, this seems like a reasonable thing to do... let me get back to you about it. Sadly, I think there isn't a quick fix or a workaround.

**Comment by alexander-mead** [comment] 2024-08-27 15:12
I've streamlined the MWE to this:
```
import twinlab as tl

import numpy as np
import pandas as pd

# Number of input and output features
num_features = 11
num_rows = 2
input_columns = [f'x_{i}' for i in range(num_features)]
output_columns = [f'y_{i}' for i in range(num_features)]
df = pd.DataFrame({
    **{col: np.random.rand(num_rows) for col in input_columns},
    **{col: np.random.rand(num_rows) for col in output_columns},
})

param_ranges = {f"x_{i}": (0,1) for i in range(num_features)}

# Intialise a Dataset object and give it a name
dataset = tl.Dataset('error_dataset')
dataset.upload(df[input_columns + output_columns])

# Emulator
emulator_id = "example_emulator"
emulator = tl.Emulator(id=emulator_id)
params = tl.TrainParams(
    estimator='gaussian_process_regression',
    input_retained_dimensions=10,
    output_retained_dimensions=10
    )
emulator.train(
    dataset=dataset,
    inputs=input_columns, 
    outputs=output_columns, 
    params=params, 
    verbose=True
)

# Recommend new points to sample
parameters = tl.RecommendParams(bounds=param_ranges)
_ = emulator.recommend(num_points=3, acq_func="LogEI", params=parameters, verbose=True) 
```

**Comment by alexander-mead** [comment] 2024-08-27 15:15
It seems that you are trying to perform Bayesian optimisation on an emulator with functional output. Can you confirm that this is the case? If so, this is currently not permitted by twinLab. Here is the error I get: `Exception: Error Code: 500 - Process recommend-purring-amusing-ballcap has failed: NotImplementedError: FunctionalGPTorch.get_candidate_points() is only supported for active learning acquisition functions.`

This error makes sense here, in that we do not currently support Bayesian optimisation on data with functional output. Can you (or maybe @Allentro) explain the use case here. What exactly would you be optimising with a functional output? Does it make sense to do this, rather than to craft a specific objective function to optimise?

**Comment by Allentro** [comment] 2024-08-27 16:35
The intent here was to explore parameter space. As you say, BO on a full field doesn't make sense. A different acquisition function was later used. 

Could the error message be refined to make this clear, please?

**Comment by alexander-mead** [comment] 2024-08-28 12:53
Yes, absolutely. I'll close this and we'll improve the error messages in due course.

**Closed as completed by alexander-mead** 2024-08-28 12:53 UTC
